jupix:
  restService:
    rootUrl: services.jupix.co.uk
    propertyPath: /api/get_properties.php
    clientId: 833815ccab44c05f8b3121c770b9c22d
    passphrase: 71899e3fefdb5a5971f7676d91c46c0a
    version: 2.0